<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="utf-8">
<style>
  body { font-family: Arial, sans-serif; color: #333; background: #f4f4f4; margin: 0; padding: 20px; }
  .card { background: #fff; border-radius: 8px; padding: 32px 40px; max-width: 580px; margin: 0 auto; }
  .header { background: linear-gradient(135deg, #1a3a6b 0%, #c41230 100%); border-radius: 8px; padding: 18px 24px; color: #fff; margin-bottom: 28px; }
  .header .brand { font-size: .75rem; opacity: .8; text-transform: uppercase; letter-spacing: .05em; margin-bottom: 4px; }
  .header h1 { margin: 0; font-size: 1.15rem; font-weight: 700; line-height: 1.3; }
  .body-text { font-size: .92rem; line-height: 1.6; color: #444; }
  .btn { display: inline-block; margin-top: 22px; padding: 11px 26px; background: linear-gradient(90deg,#1a3a6b,#c41230); color: #fff !important; border-radius: 7px; text-decoration: none; font-weight: 600; font-size: .9rem; }
  .divider { border: none; border-top: 1px solid #f0f0f0; margin: 24px 0; }
  .footer { text-align: center; font-size: .73rem; color: #aaa; margin-top: 20px; }
</style>
</head>
<body>
<div class="card">
  <div class="header">
    <div class="brand">AIRID — Project Management System</div>
    <h1>{{ $title }}</h1>
  </div>

  @if($recipientName)
  <p class="body-text">Dear <strong>{{ $recipientName }}</strong>,</p>
  @endif

  @if($body)
  <p class="body-text">{!! nl2br(e($body)) !!}</p>
  @endif

  @if($url)
  <a href="{{ $url }}" class="btn">View on Platform →</a>
  @endif

  <hr class="divider">
  <div class="footer">
    This message was automatically generated by the AIRID PMS platform.<br>
    Please do not reply to this email.
  </div>
</div>
</body>
</html>
