<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<style>
  body { font-family: Arial, sans-serif; color: #333; background: #f4f4f4; margin: 0; padding: 20px; }
  .card { background: #fff; border-radius: 8px; padding: 32px 40px; max-width: 560px; margin: 0 auto; }
  .header { background: linear-gradient(90deg, #198754, #0d6efd); border-radius: 6px; padding: 20px 24px; color: #fff; margin-bottom: 28px; }
  .header h1 { margin: 0; font-size: 1.3rem; }
  .label { font-size: .8rem; opacity: .8; }
  .badge-ok { display: inline-block; background: #d1fae5; color: #065f46; border-radius: 4px; padding: 3px 10px; font-size: .82rem; font-weight: 600; }
  .btn { display: inline-block; margin-top: 24px; padding: 12px 28px; background: linear-gradient(90deg,#1a3a6b,#c41230); color: #fff; border-radius: 6px; text-decoration: none; font-weight: 600; }
  .footer { text-align: center; font-size: .75rem; color: #999; margin-top: 28px; }
</style>
</head>
<body>
<div class="card">
  <div class="header">
    <div class="label">Project Tracking Sheet · AIRID</div>
    <h1>All Findings Resolved</h1>
  </div>

  <p>Dear <strong>{{ $recipientName }}</strong>,</p>

  <p>All non-conformity findings for the following inspection have been resolved and are ready for review and signature:</p>

  <table style="width:100%;border-collapse:collapse;margin:16px 0;">
    <tr>
      <td style="padding:8px;background:#f8f9fa;border-radius:4px;font-size:.85rem;font-weight:600;width:40%;">Study Code</td>
      <td style="padding:8px;font-size:.85rem;">{{ $projectCode }}</td>
    </tr>
    <tr>
      <td style="padding:8px;background:#f8f9fa;border-radius:4px;font-size:.85rem;font-weight:600;">Inspection</td>
      <td style="padding:8px;font-size:.85rem;">{{ $inspectionName }}</td>
    </tr>
    <tr>
      <td style="padding:8px;background:#f8f9fa;border-radius:4px;font-size:.85rem;font-weight:600;">Status</td>
      <td style="padding:8px;"><span class="badge-ok">All Resolved</span></td>
    </tr>
  </table>

  <p>Please review the QA Unit Report and apply your electronic signature where required.</p>

  <a href="{{ $reportUrl }}" class="btn">View QA Unit Report</a>

  <div class="footer">
    This message was automatically generated by the AIRID Project Tracking Sheet platform.
  </div>
</div>
</body>
</html>
