<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<style>
  body { font-family: Arial, sans-serif; color: #333; background: #f4f4f4; margin: 0; padding: 20px; }
  .card { background: #fff; border-radius: 8px; padding: 32px 40px; max-width: 560px; margin: 0 auto; }
  .header { background: linear-gradient(90deg, #1a3a6b, #c41230); border-radius: 6px; padding: 20px 24px; color: #fff; margin-bottom: 28px; }
  .header h1 { margin: 0; font-size: 1.3rem; }
  .label { font-size: .8rem; opacity: .8; }
  .btn { display: inline-block; margin-top: 24px; padding: 12px 28px; background: linear-gradient(90deg,#1a3a6b,#c41230); color: #fff; border-radius: 6px; text-decoration: none; font-weight: 600; }
  .footer { text-align: center; font-size: .75rem; color: #999; margin-top: 28px; }
</style>
</head>
<body>
<div class="card">
  <div class="header">
    <div class="label">Project Tracking Sheet · AIRID</div>
    <h1>Study Director Appointment</h1>
  </div>

  <p>Dear <strong>{{ $directorName }}</strong>,</p>

  <p>You have been appointed as <strong>Study Director</strong> for the following study:</p>

  <table style="width:100%;border-collapse:collapse;margin:16px 0;">
    <tr>
      <td style="padding:8px;background:#f8f9fa;border-radius:4px;font-size:.85rem;font-weight:600;width:40%;">Study Code</td>
      <td style="padding:8px;font-size:.85rem;">{{ $projectCode }}</td>
    </tr>
    <tr>
      <td style="padding:8px;background:#f8f9fa;border-radius:4px;font-size:.85rem;font-weight:600;">Study Title</td>
      <td style="padding:8px;font-size:.85rem;">{{ $projectTitle }}</td>
    </tr>
  </table>

  <p>You now have access to the study page where you can fill out the Study Director Appointment Form, manage study activities, and fulfil all responsibilities pertaining to your role.</p>

  <a href="{{ $projectUrl }}" class="btn">Go to the Study Page</a>

  <div class="footer">
    This message was automatically generated by the AIRID Project Tracking Sheet platform.
  </div>
</div>
</body>
</html>
